# This workflow will do a clean install of the dependencies and run tests across different versions
#
# Requires scripts:
# - bin/run_tests.R

name: Exercise tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        R: ["4.3.1"]

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}

      - name: Install project dependencies
        run: |
          install.packages(c("testthat", "jsonlite", "lintr", "dplyr", "stringr", "readr", "purrr", "tibble"))
        shell: Rscript {0}

      - name: Run exercism/r ci (runs tests) for all exercises
        run: |
          source("bin/run_tests.R")
        shell: Rscript {0}
